_parent_: configs/base.yaml

latent_dim: 512
pts_feat_dim: 4
pts_feat_pos_enc_dim: 1
evaluation:

arch:
    deformnet:
        layers_hyper: [null,256,256,256,null]
        layers_impl: [null,64,64,64,64]
        layers_pts_deformations: [null,3]
        layers_pts_feat: [null,4]
        layers_rgb: [null,3]
        interm_coord: true

    sdf_generator:
        layers_hyper: [null,256,256,256,null]
        layers_impl: [null,64,64,64,64]
        layers_rgb: [null,3]
        layers_level: [null,1]
        interm_coord: true
    
    renderer:
        lstm_dim: 32

camera:
    model: orthographic
    dist: 2.5

data:
    dataset: pix3d_pascal3d
    pix3d:
        cat: chair

eval:
    vox_res: 64
    num_points: 100000
    range: [-1.2,1.2]
    icp: false

impl:
    posenc_L: 5
    sdf_range: [-2,2]
    
image_size: [128,128]