_parent_: configs/pascal3d/base.yaml

group: reconstruction_stage_one
name: 
load: output/pascal3d/pretrain_sdf_generator/pascal3d/latest.ckpt
load_deformnet:
mean_latent:
is_stage_two_active:
eval_split: # train or val

arch:
    enc_network: resnet18
    enc_pretrained: true

data:
    dataset: pascal3d
    num_workers: 4
    augment:
        crop_scale: 0.2
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
        hue: 0.5
        rotate:
    bgcolor: 1
    pascal3d:
        set: imagenet
        cat:

impl:
    sdf_samples: 5
    depth_range: [1.2,3.8]
    importance: true
    srn_steps: 10
    rand_sample: 1024
    init_depth: 1.2
    bisection_steps: 10

loss_weight:
    render: 10
    shape_silh: 3
    ray_intsc: 1
    ray_free: 0.1
    eikonal: 1
    pts_deformations: 0

optim:
    lr: 1.e-4
    
max_epoch:

freq:
    scalar: 100 # iterations
    vis: 200 # iterations
    eval: 60 # epochs
    ckpt: 60 # epochs
    ckpt_latest: 2000 # iterations